package bam.model;

public class Testing {
    ImageTester tester = new ImageTesterCommandBuilder()
            .apiKey("<API_KEY>")
            .filePath("<FILE_PATH>")
            .appName("<APP_NAME>")
            .applitoolsURL("<APPLITOOLS_URL>")
            .matchLevel("<MATCH_LEVEL>")
            .branch("<BRANCH>")
            .parentBranch("<PARENT_BRANCH>")
            .baseline("<BASELINE>")
            .viewportSize("<VIEWPORT_SIZE>")
            .logFile("<LOG_FILE>")
            .threads(5)
            .testName("<TEST_NAME>")
            .batchName("<BATCH_NAME>")
            .batchId("<BATCH_ID>")
            .batchSequenceName("<BATCH_SEQUENCE_NAME>")
            .adjustedViewportSize("<ADJUSTED_VIEWPORT_SIZE>")
            .pixelsToCutFromSides("<PIXELS_TO_CUT_FROM_SIDES>")
            .sendBatchCompletionNotification(true)
            .splitTestsIndividually(false)
            .ignoreDisplacements(false)
            .autoPassNewTests(false)
            .accessibilityGuidelinesVersion("<ACCESSIBILITY_GUIDELINES_VERSION>")
            .ignoreRegions("<IGNORE_REGIONS>")
            .applyContentRegions("<APPLY_CONTENT_REGIONS>")
            .applyLayoutRegions("<APPLY_LAYOUT_REGIONS>")
            .pdfDPI("<PDF_DPI>")
            .pdfPageRanges("<PDF_PAGE_RANGES>")
            .pdfPassword("<PDF_PASSWORD>")
            .preservePDFNames("<PRESERVE_PDF_NAMES>")
            .closeBatchOnTestCompletion(false)
            .build();
}
